#!/bin/bash

# Process ID, used for unique filename
ID=$$

# Input setup
VLCOP="screen:// :screen-fps=30.0 :screen-caching=300 --input-slave=alsa://hw:0,0"

# Record
vlc ${VLCOP} -vvv --sout="#transcode{vcodec=h264,vb=5000,fps=30,acodec=mp4a,ab=240}:std{access=file,mux=mp4,dst=record_${ID}.m4v}"