#!/bin/bash

# Process ID, used for unique filename
ID=$$

VLCOP="screen:// :screen-fps=30.0 :screen-caching=300 --input-slave=alsa://hw:0,0"
VLCOUT="#transcode{vcodec=mp4v,acodec=mpga,vb=800,ab=128,deinterlace}:std{access=file,mux=mp4,dst=/home/greg/IgniteTech/record_${ID}.mp4}"

vlc ${VLCOP} -vvv --sout="#transcode{vcodec=h264,vb=5000,acodec=mp4a,ab=240}:std{access=file,mux=mp4,dst=record_${ID}.m4v}"